### PR TITLE
Add ASUSWrt-Merlin support and don't hardcode /root/cake-autorate

### PR DESCRIPTION
**Pull request by rany2**
This allows the user to override the default /root/cake-autorate path and should clear the path for a more standard installation.

### CODE REVIEW

**Comment by rany2** [comment]
@LiveWire1968 Please test this on your ASUSWrt router.

**Comment by LiveWire1968** [comment]
@rany2 im in Vegas until next week.

**Comment by rany2** [comment]
@LiveWire1968 No rush, thanks for confirming you're still around :)

**Comment by lynxthecat** [comment]
For the Asus Merlin users out there, what should they run to test this out? 

Something like this?

```
wget https://raw.githubusercontent.com/lynxthecat/cake-autorate/master/setup.sh
chmod +x ./setup.sh
./setup.sh lynxthecat/cake-autorate asuswrt
```

**Comment by rany2** [comment]
@lynxthecat I don't know how similar ASUSWRT is to OpenWRT so I have no idea how much of this is going to

**Comment by lynxthecat** [comment]
Also based on: https://github.com/LiveWire1968/Asus-cake-autorate

Do we need to advise about something like:

```
echo /jffs/scripts/launcher.sh >> /jffs/scripts/post-mount
```

Rather than `service enable start` (which is OpenWrt specific).

**Comment by rany2** [comment]
I don't know but maybe we could make the init.d script work on both OpenWRT and ASUSWRT.

**Comment by lynxthecat** [comment]
Sounds good. Hopefully we'll get a tester soon enough.

https://www.snbforums.com/threads/cake-autorate-adding-support-for-asus-merlin.89639

**Comment by rany2** [comment]
@lynxthecat YOUR INSTRUCTIONS ARE WRONG! 

> wget https://raw.githubusercontent.com/lynxthecat/cake-autorate/master/setup.sh

from asuswrt branch not master...

**Comment by rany2** [comment]
I'm thinking we could merge this add fix the setup.sh script as we go.

**Comment by lynxthecat** [comment]
> @lynxthecat YOUR INSTRUCTIONS ARE WRONG!
> 
> > wget https://raw.githubusercontent.com/lynxthecat/cake-autorate/master/setup.sh
> 
> from asuswrt branch not master...

Fixed!

**Comment by LiveWire1968** [comment]
@rany2 @lynxthecat 
setup.sh needs the shebang to point to /opt/bin/bash, asuswrt sh is not showing any output with printf in the script
The script then says jsonfilter and uclient-fetch are needed. uclient-fetch is not available on asuswrt.

**Comment by rany2** [comment]
@LiveWire1968 Does `wget` work and could you install jsonfitler?

**Comment by rany2** [comment]
Also could you use `/usr/bin/env sh`. I'm not going to change the shebang to something not standard just for ASUSWrt.

**Comment by LiveWire1968** [comment]
@rany2 sh does not show any output, only way to get output is "bash +x setup.sh", or change the shebang manually.
Then it shows the needed dependencies
Was able to install jsonfilter, and wget does work.

**Comment by rany2** [comment]
@LiveWire1968 is it just because of the printfs?

**Comment by LiveWire1968** [comment]
Even if I change printf to echo just to test, it doesnt show output with sh here.
`for dep in ${DEPENDENCIES}
        do
                if ! type "${dep}" >/dev/null 2>&1; then
                        echo "%s is required, please install it and rerun the script!\n" "${dep}"
                        exit_now=1
                fi`

**Comment by rany2** [comment]
Can you show me the `sh -x setup.sh` output?

**Comment by LiveWire1968** [comment]
admin@RT-AX86U-D7D0:/jffs# sh -x setup.sh
+ main
+ set -eu
+ DEPENDENCIES=jsonfilter uclient-fetch tar grep
+ REPOSITORY=lynxthecat/cake-autorate
+ BRANCH=master
+ SRC_DIR=https://github.com/lynxthecat/cake-autorate/archive/
+ API_URL=https://api.github.com/repos/lynxthecat/cake-autorate/commits/master
+ DOC_URL=https://github.com/lynxthecat/cake-autorate/tree/master#installation-on-openwrt
+ SCRIPT_PREFIX=
+ CONFIG_PREFIX=
+ MY_OS=unknown
+ unset ID_LIKE
+ . /etc/os-release
admin@RT-AX86U-D7D0:/jffs#

**Comment by LiveWire1968** [comment]
WITH bash
admin@RT-AX86U-D7D0:/jffs# bash -x setup.sh
+ main
+ set -eu
+ DEPENDENCIES='jsonfilter uclient-fetch tar grep'
+ REPOSITORY=lynxthecat/cake-autorate
+ BRANCH=master
+ SRC_DIR=https://github.com/lynxthecat/cake-autorate/archive/
+ API_URL=https://api.github.com/repos/lynxthecat/cake-autorate/commits/master
+ DOC_URL=https://github.com/lynxthecat/cake-autorate/tree/master#installation-on-openwrt
+ SCRIPT_PREFIX=
+ CONFIG_PREFIX=
+ MY_OS=unknown
+ unset ID_LIKE
+ . /etc/os-release
+ :
++ uname -o
+ '[' ASUSWRT-Merlin = ASUSWRT-Merlin ']'
+ MY_OS=asuswrt
+ '[' -z '' ']'
+ SCRIPT_PREFIX=/jffs/scripts/cake-autorate
+ '[' -z '' ']'
+ CONFIG_PREFIX=/jffs/configs/cake-autorate
+ '[' asuswrt = unknown ']'
+ '[' -d /var/run/cake-autorate ']'
+ exit_now=0
+ for dep in ${DEPENDENCIES}
+ type jsonfilter
+ for dep in ${DEPENDENCIES}
+ type uclient-fetch
+ printf '%s is required, please install it and rerun the script!\n' uclient-fetch
uclient-fetch is required, please install it and rerun the script!
+ exit_now=1
+ for dep in ${DEPENDENCIES}
+ type tar
+ for dep in ${DEPENDENCIES}
+ type grep
+ '[' 1 -ge 1 ']'
+ exit 1
admin@RT-AX86U-D7D0:/jffs#

**Comment by rany2** [comment]
@LiveWire1968 Does AsusWRT actually not have a /bin/sh?

**Comment by rany2** [comment]
Do you have some kind of IRC? I need to ask you some questions about ASUSWrt's /bin/sh

**Comment by LiveWire1968** [comment]
@rany2 #asuswrt , Rmerlin hangs in there

**Comment by rany2** [comment]
@LiveWire1968 If you could join IRC, I'm on Libera or OFTC my username is `rany`

**Comment by LiveWire1968** [comment]
@rany2 per our irc convo about init.d
Create file in /opt/etc/init.d/S99cake-autorate
 with the contents of
`#!/bin/sh
/jffs/scripts/cake-autorate/cake-autorate.sh`
chmod +x S99cake-autorate

**Pull request merged**
