### PR TITLE
Check local setup.sh script matches remote

### PR DESCRIPTION
**Pull request by lynxthecat**
Addresses #293

### CODE REVIEW

**Comment by lynxthecat** [comment]
How about this @rany2?

**Comment by rany2** [comment]
Looks good but the usage of cat here is useless. You could just pass the filename as argument to sha256sum.

**Comment by rany2** [comment]
Also I'm not sure if ASUSWrt has that.

**Review by rany2 — CHANGES_REQUESTED** [review]
Pass as argument to sha256sum and add to dependencies

**Comment by rany2** [comment]
My plan was to just have it be self replacing but this works ok too

**Comment by rany2** [comment]
Also errors should be printed to stderr.

**Comment by rany2** [comment]
I checked and you could just use `cmp` instead of `sha256sum`.

**Comment by rany2** [comment]
Just close this I'll do it myself.

**Pull request closed without merging**
