### PR TITLE
Don't use inefficient arrays to queue signal in maintain_log

### PR DESCRIPTION
**Pull request by rany2**
CC @lynxthecat

### CODE REVIEW

**Comment by rany2** [comment]
@lynxthecat can you test if negatively impacts performance on your router compared to current master?

**Comment by lynxthecat** [comment]
OK I'll test. But any loss with using arrays on signal interception (exception rather than the norm) is surely outweighed by the loss with using three tests without any signals (norm rather than the exception)?

**Comment by rany2** [comment]
@lynxthecat it's just to get an idea, i'll have it use switch-cases in a bit

**Comment by lynxthecat** [comment]
```
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.679%

root@OpenWrt-1:~/cake-autorate# cp /tmp/cake-autorate/cake-autorate.sh .
root@OpenWrt-1:~/cake-autorate# vim cake-autorate.sh
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 7.632%
```

**Comment by rany2** [comment]
@lynxthecat test now please

**Comment by lynxthecat** [comment]
OK, but isn't it getting more and more ugly!

**Comment by rany2** [comment]
@lynxthecat thanks!

**Comment by lynxthecat** [comment]
```
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.553%
```

**Comment by rany2** [comment]
@lynxthecat did you use the variant that logs out "unknown signal 0"?

**Comment by lynxthecat** [comment]
> @lynxthecat did you use the variant that logs out "unknown signal 0"?

How do you mean?

**Comment by lynxthecat** [comment]
Oh I see, I'll retest.

**Comment by lynxthecat** [comment]
```
root@OpenWrt-1:~/cake-autorate# cp /tmp/cake-autorate/cake-autorate.sh .
root@OpenWrt-1:~/cake-autorate# vim cake-autorate.sh
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.649
```

**Comment by rany2** [comment]
What's the baseline from master?

**Comment by lynxthecat** [comment]
Doing 2x head-to-head comparison. Two seconds.

**Comment by lynxthecat** [comment]
Here are 2x runs from this pull request, then 2x runs from master:

```
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.649%
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.629%
root@OpenWrt-1:~/cake-autorate# cp /tmp/cake-autorate/cake-autorate.sh .
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.607%
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.602%
```

**Comment by rany2** [comment]
I have another idea, just give me a moment @lynxthecat

**Comment by rany2** [comment]
@lynxthecat please try the current solution

**Comment by lynxthecat** [comment]
I will once I return from walking our dog!

**Comment by lynxthecat** [comment]
Why not just put the printf calls inside the traps?

**Comment by rany2** [comment]
@lynxthecat because that would just be too ugly!

**Comment by lynxthecat** [comment]
Hmm! My array solution still seems preferable on the elegance score.

**Comment by rany2** [comment]
> Hmm! My array solution still seems preferable on the elegance score.

I don't like your solution because it means an impatient user could spam cake-autorate with say an export request and cake-autorate will just mindlessly keep queueing it. This prevents this situation without any additional checks while allowing users to make, for example, both export and reset requests. Also no dynamic array sizes.

> So we are converting to hex with function call to provide string comparison with hex?

Yes, so we don't have to just match all the possible cases like we did before. I don't want to just do `signal & (1<<1)` and to be able to use a switch-case, I'd need to match all the possible cases with `1<<1` being set. So, `1<<1|1<<2` if `1<<2` was to be processed next in the switch-case order

**Comment by lynxthecat** [comment]
There is surely an easier way. How about only adding array element if unique.

**Comment by lynxthecat** [comment]
"${array[@]/$element/}" != "${array[@]}"

**Comment by rany2** [comment]
> Also I’m not sure the export spam thing is so bad. I mean we’re honouring the requests sent by the user.

It is, because you also are waiting 0.5 seconds between every time you're processing it. So it could easily mean that the user will need to restart cake-autorate.

> There is surely an easier way. How about only adding array element if unique.
>
>"${array[@]/$element/}" != "${array[@]}"

I just felt like this solution was more efficient

**Comment by lynxthecat** [comment]
> It is, because you also are waiting 0.5 seconds between every time you're processing it. So it could easily mean that the user will need to restart cake-autorate.

How do you mean?

**Comment by rany2** [comment]
> How do you mean? I mean what’s the significance of the timeout. And that’ll only be if read doesn’t return sooner.

It makes the situation of queueing up these requests with your solution so much worse.

**Comment by rany2** [comment]
Anyway how does this perform on your router, I'm  sure it's more efficient than the current implementation but by how much?

**Comment by lynxthecat** [comment]
```
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.607%
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.578%
```

**Comment by lynxthecat** [comment]
Same speedup can be given to master by just checking for null string:

```
root@OpenWrt-1:~/cake-autorate# ./bench_cpu.sh
Running CPU benchmark for test period of: 60s.
...
Average CPU usage over test period of 60s was: 6.599%
```

**Comment by rany2** [comment]
Closing as the solution was too unreadable.

**Comment by lynxthecat** [comment]
For the record, I admire the tenacity reflected in this approach. I am a huge fan of tenacity; it is surely a powerful force to be reckoned with.

**Comment by rany2** [comment]
Thanks @lynxthecat, though I was pretty disappointed in myself when I saw how simple your solution was. I have no idea why my thinking was so skewed towards this, if this were in C the initial variant of this PR would have made a ton of sense but it just kept getting more absurd until we reached this final bit with converting it to hex... :rofl: 

So that was tragic !

**Comment by rany2** [comment]
> until we reached this final bit with converting the thing to hex...

Oh, and how could I forget the masterpiece of just having a case contain all the possible combinations for a signal when I was just setting one bit at a time X)

**Pull request closed without merging**
