### PR TITLE
Resolve #163

### LINKED ISSUE #163: Issues with running as service with multi WAN
Answering @lynxthecat from #161 about running `cake-autorate` as a service with multi wan, there seems to be some inconsistencies. 

I just had following chain of events happen:

1. Had `cake-autorate` service running correctly
2. Executed `service cake-autorate stop`
3. `cake-autorate` became **disabled** and processes didn't stop (output of `ps | grep -e bash -e fping` remained the same)
4. Rebooted router, all `cake-autorate` processes disappeared
5. Enabled and started `cake-autorate` service, it started and worked correctly for both interfaces
6. Rebooted router
7. `cake-autorate` service started automatically, but this time secondary interface didn't log `DATA`
8. Executed `service cake-autorate stop`
9. This time all `cake-autorate` processes stopped, and service didn't become disabled (just stopped)
10. Executed `service cake-autorate start`
11. `cake-autorate` started but secondary instance still don't log `DATA`
12.  Executed `service cake-autorate stop`, all processes stopped, executed `service cake-autorate start` and both interfaces are logging correctly

For me, this behavior shows no logic, and I'm wondering is it `cake-autorate` or my device.

### PR DESCRIPTION
**Pull request by rany2**

### CODE REVIEW

**Comment by Quba1** [comment]
I (just because I had to stop service) tested the last version of script from #163 and unfortunately after a few hours running, stopping the service left those processes running:

```
14957 root      2464 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
14965 root      2528 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
14966 root      2464 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
14982 root      2528 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
15009 root      2568 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
15025 root      2584 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
16792 root      2532 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
16793 root      2548 S    bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
```

The version from this PR after a few starts/stops left those processes running:

```
13620 root      2464 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
13640 root      2520 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
13681 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
13697 root      2708 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
13743 root      2664 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
14758 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
```

**Comment by rany2** [comment]
Could you share `/var/run/cake-autorate/primary/proc_state` (and same for secondary) and then stop the service? It is helpful to know what these processes were

**Comment by Quba1** [comment]
```
root@OpenWrt:/tmp/run/cake-autorate/primary# cat proc_state
maintain_log_file=4976
monitor_achieved_rates=5147
maintain_pingers=5205
pinger_0=5276
monitor_0=5327

root@OpenWrt:/tmp/run/cake-autorate/secondary# cat proc_state
maintain_log_file=5014
monitor_achieved_rates=5167
maintain_pingers=5227
pinger_0=5279
monitor_0=5323

root@OpenWrt:/tmp/run# cat cake-autorate-lpids
/root/cake-autorate/cake-autorate_config.primary.sh=4879
/root/cake-autorate/cake-autorate_config.secondary.sh=4914

root@OpenWrt:/tmp/run# ps | grep -e bash -e fping
  749 root      2540 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
  751 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
  753 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
  757 root      2744 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
  760 root      1312 S    grep -e bash -e fping
 4777 root      2156 S    {cake-autorate_l} /bin/bash /root/cake-autorate/cake-autorate_launcher.sh
 4879 root      2588 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 4914 root      2588 R    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 4931 root      2520 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 4947 root      2464 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 4976 root      2564 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 5014 root      2564 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5147 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 5167 root      2576 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5205 root      2780 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 5227 root      2716 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5276 root      2144 S    fping --timestamp --loop --period 300 --interval 50 --timeout 10000 64.6.65.6 94.140.14.140 156.154.71.2 156.154.70.5 1.1.1.1 185.228.168.9
 5279 root      2144 S    fping --timestamp --loop --period 300 --interval 50 --timeout 10000 156.154.71.3 185.228.168.10 94.140.14.140 94.140.15.16 9.9.9.11 156.154.70.4
 5323 root      2700 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5327 root      2700 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh

root@OpenWrt:/tmp/run# service cake-autorate stop

root@OpenWrt:/tmp/run# ps | grep -e bash -e fping
 2107 root      2540 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 2108 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 2111 root      2736 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 2112 root      2792 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 2114 root      1312 S    grep -e bash -e fping
 4931 root      2520 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 4947 root      2464 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 4976 root      2564 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 5014 root      2564 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5147 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 5167 root      2576 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5205 root      2828 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 5227 root      2772 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5323 root      2700 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 5327 root      2700 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
```

This attempt left the biggest number of processes so far.

**Comment by rany2** [comment]
@lynxthecat Somehow monitor doesn't seem to get killed with multiple instances, doesn't make much sense (to me at least).

**Comment by rany2** [comment]
Perhaps me going back to using `-u` broke it, lemme try and revert that now.

**Comment by rany2** [comment]
@Quba1 can you try now?

**Comment by rany2** [comment]
@Quba1 Also kill all these processes before you attempt once again, do something like `ps | grep -e  cake-autorate -e fping | awk '{print $1}' | xargs kill -9`

**Comment by lynxthecat** [comment]
I've been trying to think of how multiple instances might conflict. File descriptors are always unique for different process families (cake-autorate main) sharing the same ultimate originating process (launcher) right? And I don't think we share any paths that conflict since separate run directories.

**Comment by rany2** [comment]
@lynxthecat there is some weirdness with read -u, at least when I was reworking the sleep funcs.... maybe it's better to just avoid it all together.

**Comment by Quba1** [comment]
This is a result of using 2461ddf. I started from a rebooted device.

```
root@OpenWrt:~/cake-autorate# ps | grep -e bash -e fping
 8966 root      1312 S    grep -e bash -e fping

root@OpenWrt:~/cake-autorate# service cake-autorate enable

root@OpenWrt:~/cake-autorate# ps | grep -e bash -e fping
 9017 root      1312 S    grep -e bash -e fping

root@OpenWrt:~/cake-autorate# service cake-autorate start

root@OpenWrt:~/cake-autorate# ps | grep -e bash -e fping
 9054 root      2156 S    {cake-autorate_l} /bin/bash /root/cake-autorate/cake-autorate_launcher.sh
 9083 root      2588 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9094 root      2588 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9102 root      2504 R    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9106 root      2504 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9112 root      2528 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9133 root      2528 R    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9203 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9239 root      2648 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9260 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9305 root      2648 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
10218 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
10243 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
10248 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
10257 root      2612 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
10258 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
10266 root      1312 S    grep -e bash -e fping
10269 root      2612 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh

root@OpenWrt:~/cake-autorate# cat /tmp/run/cake-autorate/primary/proc_state; cat /tmp/run/cake-autorate-lpids; cat /tmp/run/cake-autorate/secondary/proc_state; ps | grep -e bash -e fping
maintain_log_file=9112
monitor_achieved_rates=9203
maintain_pingers=9239
/root/cake-autorate/cake-autorate_config.primary.sh=9083
/root/cake-autorate/cake-autorate_config.secondary.sh=9094
maintain_log_file=9133
monitor_achieved_rates=9260
maintain_pingers=9305
 9054 root      2156 S    {cake-autorate_l} /bin/bash /root/cake-autorate/cake-autorate_launcher.sh
 9083 root      2588 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9094 root      2588 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9102 root      2504 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9106 root      2504 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9112 root      2528 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9133 root      2528 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9203 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9239 root      2648 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9260 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9305 root      2648 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
22493 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
22498 root      2524 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
22500 root      2612 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
22502 root      2612 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
22507 root      1312 R    grep -e bash -e fping

root@OpenWrt:~/cake-autorate# service cake-autorate stop

root@OpenWrt:~/cake-autorate# ps | grep -e bash -e fping
 9102 root      2504 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9106 root      2504 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9112 root      2528 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9133 root      2528 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9203 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9239 root      2648 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
 9260 root      2560 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
 9305 root      2648 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
23351 root      2612 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.secondary.sh
23353 root      2612 S    {cake-autorate.s} /bin/bash /root/cake-autorate/cake-autorate.sh /root/cake-autorate/cake-autorate_config.primary.sh
23355 root      1312 S    grep -e bash -e fping
```

One thing I noticed is that processes with the high pids are changing their pids very fast. No idea what that means.

**Comment by rany2** [comment]
> I've been trying to think of how multiple instances might conflict. File descriptors are always unique for different process families (cake-autorate main and children for each instance) sharing the same ultimate originating process (launcher), right? And I don't think we share any paths that conflict since separate run directories.

Yep, that's why this is catching me off guard. I'm not sure where to look

**Comment by rany2** [comment]
@Quba1 maybe it's your config, mind sharing it?

**Comment by rany2** [comment]
This is so strange because you seem to be effortlessly replicating this issue ..

**Comment by Quba1** [comment]
> @Quba1 maybe it's your config, mind sharing it?

There you go.

```
root@OpenWrt:~/cake-autorate# cat cake-autorate_config.primary.sh
#!/bin/bash

# *** STANDARD CONFIGURATION OPTIONS ***

### For multihomed setups, it is the responsibility of the user to ensure that the probes
### sent by this instance of cake-autorate actually travel through these interfaces.
### See ping_extra_args and ping_prefix_string

dl_if=ifb4eth0 # download interface
ul_if=eth0     # upload interface

# Set either of the below to 0 to adjust one direction only
# or alternatively set both to 0 to simply use cake-autorate to monitor a connection
adjust_dl_shaper_rate=1 # enable (1) or disable (0) actually changing the dl shaper rate
adjust_ul_shaper_rate=1 # enable (1) or disable (0) actually changing the ul shaper rate

min_dl_shaper_rate_kbps=3000  # minimum bandwidth for download (Kbit/s)
base_dl_shaper_rate_kbps=12000 # steady state bandwidth for download (Kbit/s)
max_dl_shaper_rate_kbps=60000  # maximum bandwidth for download (Kbit/s)

min_ul_shaper_rate_kbps=3000  # minimum bandwidth for upload (Kbit/s)
base_ul_shaper_rate_kbps=12000 # steady state bandwidth for upload (KBit/s)
max_ul_shaper_rate_kbps=40000  # maximum bandwidth for upload (Kbit/s)

# *** OVERRIDES ***

### See cake-autorate_defaults.sh for additional configuration options
### that can be set in this configuration file to override the defaults.
### Place any such overrides below this line.

ping_prefix_string="mwan3 use wan exec"
dl_delay_thr_ms=25 # (milliseconds)
ul_delay_thr_ms=25 # (milliseconds)

# *** DO NOT EDIT BELOW THIS LINE ***

config_file_check="cake-autorate"
```

```
root@OpenWrt:~/cake-autorate# cat cake-autorate_config.secondary.sh
#!/bin/bash

# *** STANDARD CONFIGURATION OPTIONS ***

### For multihomed setups, it is the responsibility of the user to ensure that the probes
### sent by this instance of cake-autorate actually travel through these interfaces.
### See ping_extra_args and ping_prefix_string

dl_if=ifb4eth4 # download interface
ul_if=eth4     # upload interface

# Set either of the below to 0 to adjust one direction only
# or alternatively set both to 0 to simply use cake-autorate to monitor a connection
adjust_dl_shaper_rate=1 # enable (1) or disable (0) actually changing the dl shaper rate
adjust_ul_shaper_rate=1 # enable (1) or disable (0) actually changing the ul shaper rate

min_dl_shaper_rate_kbps=3000  # minimum bandwidth for download (Kbit/s)
base_dl_shaper_rate_kbps=12000 # steady state bandwidth for download (Kbit/s)
max_dl_shaper_rate_kbps=100000  # maximum bandwidth for download (Kbit/s)

min_ul_shaper_rate_kbps=3000  # minimum bandwidth for upload (Kbit/s)
base_ul_shaper_rate_kbps=12000 # steady state bandwidth for upload (KBit/s)
max_ul_shaper_rate_kbps=50000  # maximum bandwidth for upload (Kbit/s)

# *** OVERRIDES ***

### See cake-autorate_defaults.sh for additional configuration options
### that can be set in this configuration file to override the defaults.
### Place any such overrides below this line.

ping_prefix_string="mwan3 use wanb exec"
dl_delay_thr_ms=20 # (milliseconds)
ul_delay_thr_ms=20 # (milliseconds)

# *** DO NOT EDIT BELOW THIS LINE ***

config_file_check="cake-autorate"
``

**Comment by Quba1** [comment]
> This is so strange because you seem to be effortlessly replicating this issue ..

I mean... I'm not happy about that either. Maybe I do something accidentally, but I'm as transparent with my tests methodology as possible.

**Comment by rany2** [comment]
Something is borked on your end anyway, why is there no fping running?

**Comment by rany2** [comment]
Are you sure `mwan3 use wan exec wget -qO- icanhazip.com` runs?

**Comment by Quba1** [comment]
> Are you sure `mwan3 use wan exec wget -qO- http://icanhazip.com` runs?

Runs fine for both interfaces, same with `mwan3 use wan exec fping 8.8.8.8`

**Comment by Quba1** [comment]
> Something is borked on your end anyway, why is there no fping running?

I have no idea why there's no fping. `cake-autorate` runs fine tho.

**Comment by lynxthecat** [comment]
Facilitating multiple concurrent instances adds quite a lot of complexity to get right and has not been tested since the recent major overhaul. With your help we will figure it out.

**Comment by rany2** [comment]
@Quba1 Just making sure of one thing, this doesn't happen if you run cake-autorate.sh individually _WITHOUT_ the launcher?

**Comment by Quba1** [comment]
> @Quba1 Just making sure of one thing, this doesn't happen if you run multiple cake-autorate.sh instances individually _WITHOUT_ the launcher?

How do you recommend running two instances without the launcher? Just starting `cake-autorate.sh` in the background or somehow else?

**Comment by rany2** [comment]
@Quba1 you could run both `cake-autorate.sh <path to primary config>` and `cake-autorate.sh <path to secondary config>` in two different terminals. See if that works as intended.

**Comment by Quba1** [comment]
Now it stopped working both standalone and as a service

```
ERROR; 2023-02-18-10:45:45; 1676717145.881677; /root/cake-autorate/cake-autorate.sh: line 207: &13: No such file or directory
```

This might have happened after switching to 2461ddf cause I'm not sure if I checked logs after that.

**Comment by rany2** [comment]
Could you try to run the setup script provided but replace lynxthecat with rany2 and master with patch-1.

**Comment by Quba1** [comment]
I have run setup script from `patch-1` and then ran two instances manually.

First time both instances started correctly and both stopped correctly. Second try, both instances started correctly. Then primary instance (first killed) stopped fully. But secondary instance kept printing `LOAD` statements.

This is the moment of killing second instance:

```
DATA; 2023-02-18-11:14:57; 1676718897.940367; 1676718897.938637; 11; 15; 0; 0; 1676718897.912250; 94.140.15.16; 59; 19475; 23350; 4276; 3875; 21029; 19475; 23350; 4276; 3875; 21029; 0; 0; dl_idle; ul_idle; 12000; 12000
DATA; 2023-02-18-11:14:58; 1676718898.003757; 1676718898.001152; 11; 15; 0; 0; 1676718897.974200; 185.228.168.10; 59; 19368; 24250; 4037; 4882; 21029; 19368; 24250; 4037; 4882; 21029; 0; 0; dl_idle; ul_idle; 12000; 12000
LOAD; 2023-02-18-11:14:58; 1676718898.009481; 1676718898.008271; 20; 205; 12000; 12000
DATA; 2023-02-18-11:14:58; 1676718898.061079; 1676718898.059168; 20; 205; 0; 1; 1676718898.035140; 156.154.71.2; 59; 19869; 24750; 3310; 4881; 21029; 19869; 24750; 3310; 4881; 21029; 0; 0; dl_idle; ul_idle; 12000; 12000
^CDEBUG; 2023-02-18-11:14:58; 1676718898.126296; Starting: cleanup_and_killall with PID: 11550
INFO; 2023-02-18-11:14:58; 1676718898.130688; Stopping cake-autorate with PID: 11550 and config: cake-autorate_config.secondary.sh
INFO; 2023-02-18-11:14:58; 1676718898.133737; Killing all background processes and cleaning up temporary files.
DEBUG; 2023-02-18-11:14:58; 1676718898.159774; Starting: kill_maintain_pingers with PID: 11616
DEBUG; 2023-02-18-11:14:58; 1676718898.169819; Terminating maintain_pingers.
DEBUG; 2023-02-18-11:14:58; 1676718898.174788; Killing fping instance.
DEBUG; 2023-02-18-11:14:58; 1676718898.180627; Starting: kill_pinger with PID: 11616
LOAD; 2023-02-18-11:14:58; 1676718898.217489; 1676718898.216507; 32; 13; 12000; 12000
LOAD; 2023-02-18-11:14:58; 1676718898.424673; 1676718898.423727; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:14:58; 1676718898.634412; 1676718898.633468; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:14:58; 1676718898.844353; 1676718898.843387; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:14:59; 1676718899.054518; 1676718899.053577; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:14:59; 1676718899.268221; 1676718899.266774; 2; 0; 12000; 12000
ERROR; 2023-02-18-11:14:59; 1676718899.266568; /root/cake-autorate/cake-autorate_lib.sh: line 64: 11616 Killed                  "${@}"
LOAD; 2023-02-18-11:14:59; 1676718899.474622; 1676718899.473684; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:14:59; 1676718899.684902; 1676718899.683814; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:14:59; 1676718899.894613; 1676718899.893677; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:15:00; 1676718900.104495; 1676718900.103549; 2; 2; 12000; 12000
LOAD; 2023-02-18-11:15:00; 1676718900.314300; 1676718900.313311; 0; 0; 12000; 12000
LOAD; 2023-02-18-11:15:00; 1676718900.528230; 1676718900.526734; 140; 27; 12000; 12000
LOAD; 2023-02-18-11:15:00; 1676718900.734087; 1676718900.733158; 58; 31; 12000; 12000
LOAD; 2023-02-18-11:15:00; 1676718900.944901; 1676718900.943942; 205; 36; 12000; 12000
```

**Comment by lynxthecat** [comment]
@rany2 this looks similar to that issue I faced when I amended cake-autorate.sh during a run. Could it be related to running two instances from the same script from a common ultimate parent process? 

@Quba1 please could you try the 'stable' branch? It would require going back to the old config format in which everything is in one file for each instance. If the stable branch works fine for multiple instances (and I believe at least one person tested that) then the present failure mode relates to the recent overhaul between the two branches.

**Comment by rany2** [comment]
> Could it be related to running two instances from the same script from a common ultimate parent process?

I doubt it. I mean we aren't doing anything special in the launcher.

**Comment by Quba1** [comment]
@lynxthecat Stable seems to be working fine, both when run manually and as a service. The only time things broke was when I accidentally called `service cake-autorate start` while service was running, and then the behaviour was similar to that observed in `master`

**Comment by Quba1** [comment]
> @lynxthecat Stable seems to be working fine, both when run manually and as a service. The only time things broke was when I accidentally called `service cake-autorate start` while service was running, and then the behaviour was similar to that observed in `master`

However shortly after testing that I switched to 'master' because the internet latency on 'stable' was unbearable (which wasn't a thing with v1.1.0 and single connection). I know this is more an anecdotal evidence, but when I switched from 'stable' to 'master' Twitch livestream I was watching immediately automatically increased resolution and stopped stuttering.

**Comment by lynxthecat** [comment]
@Quba1 does this make things work for you:

https://github.com/lynxthecat/cake-autorate/tree/lynxthecat-patch-1

**Pull request closed without merging**
