### PR TITLE
Minor changes for the release

### PR DESCRIPTION
**Pull request by rany2**

### CODE REVIEW

**Comment by rany2** [comment]
@lynxthecat Could you test this in this state? I won't be pushing any changes anymore

**Comment by rany2** [comment]
Why https://github.com/lynxthecat/cake-autorate/pull/206/commits/2633d365f81b9a7d83871c335459f920728a6d13? It hurts readability and brings no performance improvements

**Comment by lynxthecat** [comment]
I started looking into it from perspective of shaper_rate_kbps_str - the _str jarred. So I thought about making it something like new_shaper_rate_kbps. And then it dawned on me that we have set_shaper_rates() and set_cake_rate(), which also jarred. So I thought actually why not just fold it all into the one function. It's actually simpler and avoids messing about with the assignments and variable names and awkwardness over set_shaper_rates() vs set_cake_rate(). It seems simpler to me to have all of this in just the set_shaper_rates() function?

**Comment by lynxthecat** [comment]
Could be squashed with: https://github.com/rany2/cake-autorate/commit/137d5b05d26df9739e432c3f1fd9a2da7a536097?

**Comment by rany2** [comment]
@lynxthecat Personally I'm not a fan of this but I don't feel strongly about it. I just don't like how you repeated code instead of reusing the same function.

**Comment by rany2** [comment]
> Could be squashed with: [rany2@137d5b0](https://github.com/rany2/cake-autorate/commit/137d5b05d26df9739e432c3f1fd9a2da7a536097)?

Sure

**Comment by lynxthecat** [comment]
Actually you're causing me to doubt now. 

Maybe the old formulation was indeed better, but with `new_shaper_rate_kbps` rather than `shaper_rate_kbps_str`. 

Are your git skills sufficient to undo undo the squash, and undo my commit, and then just change the _str to _new?

**Comment by rany2** [comment]
> Actually I see what you mean now.
> 
> Maybe the old formulation was indeed better, but with `new_shaper_rate_kbps` rather than `shaper_rate_kbps_str`.
> 
> Are your git skills sufficient to undo the squash, and undo my commit, and then just change the `shaper_rate_kbps_str` to `new_shaper_rate_kbps`?

Sure

**Comment by lynxthecat** [comment]
Sorry!

**Comment by rany2** [comment]
> Sorry!

No worries

**Comment by lynxthecat** [comment]
Nice work and runs fine for me. Many thanks.

**Pull request merged**
