### PR TITLE
Improve cake-autorate_setup script

### PR DESCRIPTION
**Pull request by rany2**
@lynxthecat please test it

### CODE REVIEW

**Comment by lynxthecat** [comment]
```
root@OpenWrt-1:~/cake-autorate# ./cake-autorate_setup.sh
jsonfilter is /usr/bin/jsonfilter
uclient-fetch is /bin/uclient-fetch
tar is /bin/tar
grep is /bin/grep
Installing cake-autorate in /root/cake-autorate...
tar: invalid magic
tar: short read
```

**Comment by lynxthecat** [comment]
`./cake-autorate_setup.sh: line 41: syntax error: unexpected "fi" (expecting "then")`

**Comment by rany2** [comment]
@lynxthecat hopefully that is done, I should just install openwrt on some VM to test :')

**Comment by lynxthecat** [comment]
With the missing 'then':

```
root@OpenWrt-1:~/cake-autorate# ./cake-autorate_setup.sh
Installing cake-autorate in /root/cake-autorate...
mv: can't rename '/tmp/tmp.FafFja/cake-autorate-master/*': No such file or directory
```

**Comment by rany2** [comment]
@lynxthecat try now

**Comment by lynxthecat** [comment]
```
root@OpenWrt-1:~/cake-autorate# ./cake-autorate_setup.sh
Installing cake-autorate in /root/cake-autorate...
Previous configuration present - keep it? [Y/n]
Using prior configuration

2.0.0 successfully installed, but not yet running

Start the software manually with:
   cd /root/cake-autorate; ./cake-autorate.sh
Run as a service with:
   service cake-autorate enable; service cake-autorate start

root@OpenWrt-1:~/cake-autorate#
root@OpenWrt-1:~/cake-autorate# ls
cake-autorate.sh                     cake-autorate_defaults.sh            cake-autorate_setup.sh
cake-autorate_config.primary.sh      cake-autorate_launcher.sh            version.txt
cake-autorate_config.primary.sh.new  cake-autorate_lib.sh
root@OpenWrt-1:~/cake-autorate# cat version.txt
version = 2.0.0
commit = df5e67994d06b96725eb252474b8b1acda8f3723
```

**Comment by rany2** [comment]
@lynxthecat looks good, no?

**Comment by lynxthecat** [comment]
Looks good. Any way to make the setup.sh file automatically download with executable bit set?

**Comment by rany2** [comment]
wdym? executable bit set for what?

**Comment by lynxthecat** [comment]
chmod +x to ./setup.sh

**Comment by rany2** [comment]
nope, but no need to chmod it if you run it with sh directly. So `sh ./setup.sh`  instead of `./setup.sh`.

**Comment by lynxthecat** [comment]
Ah yes, gotcha. Don't suppose you could be motivated to rename the files as well? I'd understand entirely if not.

**Comment by rany2** [comment]
I don't mind, but I'd rather do that it in another PR. If you think this is fine so far, merge this and I'll make another to rename the files.

**Comment by lynxthecat** [comment]
Sweet! Yes sure.

**Pull request merged**
