### PR TITLE
Fix errors in setup script

### PR DESCRIPTION
**Pull request by richb-hanover**
…not developer's repo)

### CODE REVIEW

**Comment by richb-hanover** [comment]
- Re-enable the opkg commands
- Point to proper repo (main repo, not developer's repo)

**Comment by lynxthecat** [comment]
Thanks @richb-hanover!

**Comment by richb-hanover** [comment]
Thanks! (I'm so embarrassed)

**Comment by lynxthecat** [comment]
Don't be. GitHub is pretty new to me. I only just learnt how to log in on the command line to revert commits. It seems immensely powerful and well made.

**Pull request merged**
