### PR TITLE
Use comma as delimiter for tsping

### LINKED ISSUE #246: tsping mode is not compatible with mwan3
Some time ago, the code was changed to pass `--machine-readable=' '` argument to tsping. Unfortunately, the `mwan3 use lte exec` wrapper (prefix command) mangles this. It is a bug in `mwan3`, but bugs there are never fixed. So please try to avoid triggering it. In other words, please try to avoid the need for any special characters that need quoting or otherwise cannot pass through the `$*` construct, such as spaces. Maybe use $IFS that includes the comma when parsing.

### PR DESCRIPTION
**Pull request by rany2**
Using "mwan3 use X ..." for tsping does not work properly due to the developers calling "..." using $*. This works around the issue by using `,` as the delimiter instead.

Fixes #246

### CODE REVIEW

**Comment by lynxthecat** [comment]
Unfortunately this breaks tsping - no reflector responses are read in.

**Comment by rany2** [comment]
@lynxthecat I could see responses on my end, at any rate could you try now?

**Comment by lynxthecat** [comment]
Still not working.

**Comment by lynxthecat** [comment]
It works with:

```
 565 parse_preprocessor()
 566 {
 567         # prepend REFLECTOR_RESPONSE and append timestamp as a checksum
 568         while IFS=', ' read -r timestamp remainder
```

Won't this issue affect the other ping binaries too?

**Pull request merged**
